version: "3.8"
services:
  db:
    image: postgres:13-alpine
    container_name: quiz_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=quiz
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db


volumes:
  postgres_data: